### ISSUE TITLE
Detailed setting of hyper parameters

### ISSUE THREAD

**Issue by wanghao14** [MalongTech/research-ms-loss#10]
The setting of hyper parameters we can refer is just the example.yaml, but as you said in your paper, you have experimented on more than one dataset. How to set the hyper parameters for those datasets? Please give more config file for reference, thanks.

**Comment by wanghao14** [comment]
One more question, does your code support multiple-gpus training? I want to realize the distributed training by torch.distributed, but the specific method for data loading like RandomIdentitySampler making it seem difficult.

**Comment by mscottml** [comment]
Hi @wanghao14 ,

We've released the details of one dataset, CUB, because it is a representative example. In fact the results are even a bit higher than in the paper. For other datasets, we leave this up to the reader. 

Our code can be adapted to support multiple GPU training. But the purpose of our repo is to focus on the algorithm, to help readers of our paper. Engineering enhancements are out of scope.
